### ISSUE TITLE
npm run build error

### ISSUE THREAD

**Issue by Leotw** [easy-team/easywebpack-cli#21]
import png格式的图片会报如下错误，svg格式的不会：
`[easywebpack-cli] [/Users/tiwenleo/Liu/my/egg-stream-more/node_modules/webpack-tool/lib/tool.js] webpack build error { Error: spawn /Users/tiwenleo/Liu/my/egg-stream-more/node_modules/optipng-bin/vendor/optipng ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:19)
    at onErrorNT (internal/child_process.js:427:16)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
`

**Comment by hubcarl** [comment]
@Leotw 可能是png压缩兼容性，可以禁用 imagemin-webpack-plugin
